#!/usr/bin/env sh
# Executa o Commitlint que está DENTRO do commitlint-template
node "$(dirname "$0")/../node_modules/@commitlint/cli/cli.js" \
  --config "$(dirname "$0")/../commitlint.config.cjs" \
  --edit "$1"
